# Generated by Django 3.2.16 on 2022-10-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email_adress',
            new_name='email_address',
        ),
    ]
